config/routes.rb
Rails.application.routes.draw do
  # get 'subjects/index'
  # get 'students/index'
  resources :subjects
  resources :students do
    post :add_marks, on: :collection
  end
  root 'students#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :student_subjects
  has_many :subjects, through: :student_subjects
end

app/models/student_subject.rb
class StudentSubject < ApplicationRecord
  belongs_to :student
  belongs_to :subject
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :student_subjects
  has_many :students, through: :student_subjects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @student = Student.all
    @subject = Subject.all
  end

  def add_marks
    value = StudentSubject.where(student_id: params[:student_id], subject_id:
      params[:subject_id]).present?
    if value
      StudentSubject.where(student_id: params[:student_id], subject_id: 
      params[:subject_id]).first.update(mark: params[:mark])
    else
    student = Student.find(params[:student_id])
    std_assign = student.student_subjects.build(subject_id: params[:subject_id], mark: params[:mark])
    std_assign.save
    end
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  def index
    @subject = Subject.all

  def new
   @subject = Subject.new
  end

  def show
    
  end

      
  def create
    @subject = Subject.new(sub_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to subjects_path, notice: 'new subject.' }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def sub_params
      params.require(:subject).permit(:name, :code)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarkList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/index.html.erb
<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
.input_mark{
  width: 110px;
}
</style>

<table  style="width:100%">
  <tr>
    <th><input type="checkbox" id = "select_all"> Select all</th>
    <th>Roll no:</th> 
    <th>Name</th>
    <th>Email</th>
    <%@subject.each do |sub| %>
    <th><%= sub.name%></th> 
    <% end %>
    <th>Total/600:</th> 
  </tr>

  <% @student.each do |student| %>
    <tr id="<%= student.id %>">
      <td><input type="checkbox"class="cb" id="checkbox"></td>
      <td><%= student.id%></td>
      <td><%= student.name%></td>
      <td><%= student.email%></td>
      <% @subject.each do | sub| %>
      <td>
        <input type="text" student="<%= student.id %>" subject="<%= sub.id %>" class="input_mark" value="<%= student.student_subjects.where(subject_id: sub.id).
        first.try(:mark)%>">
      </td>
      <% end %>
      <td class="last"></td>
    </tr>
  <% end %>
</table>

<div class ="result_show">
  <p id = "selected_students"></p>
  <p id = "total_marks"></p>
  <p id = "percentage"></p>
</div>

<script type="text/javascript">
  var url = "<%= add_marks_students_path %>";

  $('.input_mark').change(function(){
    var student = $(this).attr('student');
    var subject = $(this).attr('subject');
    var mark = $(this).val();
    var params = {
      student_id: student,
      subject_id: subject,
      mark: mark
    }
    postData(url, params, function(data) {
      // console.log(data);
    });
  });

  function postData(url, params, callback) {
    $.ajax({
      type: "POST",
      url:url,
      dataType: "json",
      data: params,
      success: function( data ) {
        callback(data);
      },
      error: function(data){
        callback(data);
      }
    });
  };

  var selected_students = 0;
        
  $("#select_all").click(function () {
    $(".cb").prop('checked', $(this).prop('checked'));
    calculate();
  });
  $('.cb').change(function(){ 
    if(false == $(this).prop("checked")){ 
      $("#select_all").prop('checked', false); 
    }
    if ($('.cb:checked').length == $('.cb').length ){
      $("#select_all").prop('checked', true);
    }
  });

  $(".cb").change(function(){
    calculate();
  });

  function calculate() {
    var total_marks = 0;
    var  percentage = 0;

    $("#checkbox:checked").each(function () {
      var each_total = 0;
      var mark = 0;

      $(this).closest("tr").find(".input_mark").each(function(){
        mark = parseFloat($(this).val());
        each_total += mark;
      });
      $(this).closest("tr").find(".last").html(each_total);
      total_marks += each_total;
    });

    selected_students = $("#checkbox:checked").length;
    $("#selected_students").html("Total selected students:" + selected_students); 
    $("#total_marks").html("Total marks:" + total_marks); 
    percentage = (total_marks*100)/(selected_students*600);
    $("#percentage").html("Total percentage:"+ percentage);

    $('.cb').not(':checked').each(function(){
     $(this).closest("tr").find(".last").html('');
    }); 

    if(selected_students == 0){
      $(".result_show").hide();
    } else {
      $(".result_show").show();
    }
  };
</script>

app/views/subjects/_form.html.erb
<%= simple_form_for(@subject) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :code%>
  </div>
 
  <div class="form-actions">
    <%= f.button :submit %>  
  </div>
  
<% end %>

app/views/subjects/index.html.erb
<h1>Subjects#index</h1>
<p>Find me in app/views/subjects/index.html.erb</p>
<% @subject.each do |sub| %>

 <%= sub.name %>
 <%= sub.code %><br>

<% end %>
<%= link_to 'New ', new_subject_path  %>

app/views/subjects/new.html.erb
<%= render 'form', subject: @subject %>